language: java
before_install:
  - unset GEM_PATH
install: 
  - mvn -e -Pjenkins,snapshotRepo install -DskipTests=true -B
script: 
  - mvn -e -Pjenkins,snapshotRepo verify
jdk:
  - openjdk7
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
